version: '3'
services:
  # Elasticsearch engine (node #1, the main node)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch2
    depends_on:
      - elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.zen.ping.unicast.hosts: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  # Search browser
  dejavu:
    image: appbaseio/dejavu:2.0.5
    container_name: dejavu
    depends_on:
      - elasticsearch
    ports:
      - 1358:1358

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.3
    depends_on:
      - elasticsearch
    container_name: kibana
    environment:
      SERVER_NAME: kibana-server
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet

  cerebro:
    image: yannart/cerebro:0.8.1
    container_name: cerebro
    depends_on:
      - elasticsearch
    environment:
      http.port: 9000
    ports:
      - 9000:9000

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
